### PR TITLE
bug: PhpdocAlignFixer - fix static @method

### LINKED ISSUE #5867: Rule `phpdoc_align` doesn't work with both @method static and not
## Bug report

php version : `8.0.9 (built: Jul 30 2021 13:03:39)`
php-cs-fixer version : `3.0.2`

command :
```bash
$ php vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --allow-risky=yes --dry-run --diff -vvv
PHP CS Fixer 3.0.2 Constitution by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.9
Loaded config default from ".php-cs-fixer.php".
Using cache file ".php-cs-fixer.cache".
SSSSSSSSSFSFSSSSSSSSFSSFSSSSSSSSSSSSSFFFFFSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                                                                                                                                            80 / 80 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

   6) src/Infrastructure/Faker/Factory/CustomerFactory.php (phpdoc_align)
      ---------- begin diff ----------
--- /home/me/Documents/Projets/project/src/Infrastructure/Faker/Factory/CustomerFactory.php
+++ /home/me/Documents/Projets/project/src/Infrastructure/Faker/Factory/CustomerFactory.php
@@ -11,19 +11,19 @@
 use Zenstruck\Foundry\RepositoryProxy;
 
 /**
- * @method static Customer|Proxy createOne(array $attributes = [])
- * @method static Customer[]|Proxy[] createMany(int $number, $attributes = [])
- * @method static Customer|Proxy find($criteria)
- * @method static Customer|Proxy findOrCreate(array $attributes)
- * @method static Customer|Proxy first(string $sortedField = 'id')
- * @method static Customer|Proxy last(string $sortedField = 'id')
- * @method static Customer|Proxy random(array $attributes = [])
- * @method static Customer|Proxy randomOrCreate(array $attributes = [])
- * @method static Customer[]|Proxy[] all()
- * @method static Customer[]|Proxy[] findBy(array $attributes)
- * @method static Customer[]|Proxy[] randomSet(int $number, array $attributes = [])
- * @method static Customer[]|Proxy[] randomRange(int $min, int $max, array $attributes = [])
- * @method static CustomerRepository|RepositoryProxy repository()
+ * @method static         Customer|Proxy createOne(array $attributes = [])
+ * @method static         Customer[]|Proxy[] createMany(int $number, $attributes = [])
+ * @method static         Customer|Proxy find($criteria)
+ * @method static         Customer|Proxy findOrCreate(array $attributes)
+ * @method static         Customer|Proxy first(string $sortedField = 'id')
+ * @method static         Customer|Proxy last(string $sortedField = 'id')
+ * @method static         Customer|Proxy random(array $attributes = [])
+ * @method static         Customer|Proxy randomOrCreate(array $attributes = [])
+ * @method static         Customer[]|Proxy[] all()
+ * @method static         Customer[]|Proxy[] findBy(array $attributes)
+ * @method static         Customer[]|Proxy[] randomSet(int $number, array $attributes = [])
+ * @method static         Customer[]|Proxy[] randomRange(int $min, int $max, array $attributes = [])
+ * @method static         CustomerRepository|RepositoryProxy repository()
  * @method Customer|Proxy create($attributes = [])
  */
 class CustomerFactory extends ModelFactory

      ----------- end diff -----------

```

config file : 
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . "/src");

$config = new PhpCsFixer\Config();
return $config
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PSR12' => true,
        '@PHP80Migration' => true,
        '@PHP80Migration:risky' => true,
        'phpdoc_to_comment' => false,
        'strict_param' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder($finder);
```

### Code snippet that reproduces the problem

  ```php
<?php
/**
 * @method static Customer|Proxy createOne(array $attributes = [])
 * @method static Customer[]|Proxy[] createMany(int $number, $attributes = [])
 * @method static Customer|Proxy find($criteria)
 * @method static Customer|Proxy findOrCreate(array $attributes)
 * @method static Customer|Proxy first(string $sortedField = 'id')
 * @method static Customer|Proxy last(string $sortedField = 'id')
 * @method static Customer|Proxy random(array $attributes = [])
 * @method static Customer|Proxy randomOrCreate(array $attributes = [])
 * @method static Customer[]|Proxy[] all()
 * @method static Customer[]|Proxy[] findBy(array $attributes)
 * @method static Customer[]|Proxy[] randomSet(int $number, array $attributes = [])
 * @method static Customer[]|Proxy[] randomRange(int $min, int $max, array $attributes = [])
 * @method static CustomerRepository|RepositoryProxy repository()
 * @method Customer|Proxy create($attributes = [])
 */
class CustomerFactory extends ModelFactory
{}
  ```

### PR DESCRIPTION
**Pull request by HypeMC**
Fixes #5867

### CODE REVIEW

File: src/Fixer/Phpdoc/PhpdocAlignFixer.php [hunk 1]
```diff
@@ -351,19 +373,31 @@ private function getMatches(string $line, bool $matchCommentOnly = false): ?arra
                 $matches['tag'] = $matches['tag3'];
                 $matches['hint'] = $matches['hint3'];
                 $matches['var'] = $matches['signature'];
+
+                // Since static can be both a return type declaration & a keyword that defines static methods
+                // we assume it's a type declaration when only one value is present
+                if ('' === $matches['hint'] && '' !== $matches['static']) {
+                    $matches['hint'] = $matches['static'];
+                    $matches['static'] = '';
+                }
```
Comment (julienfalque) [inline src/Fixer/Phpdoc/PhpdocAlignFixer.php:382]: I think this is not covered by added tests.

Comment (HypeMC) [reply src/Fixer/Phpdoc/PhpdocAlignFixer.php:382]: @julienfalque Hi, this case is in fact covered by line 1116 https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/63740ece1ea08855db4895d9c8b5d2e904b1e9fc/tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php#L1111-L1122

Comment (julienfalque) [reply src/Fixer/Phpdoc/PhpdocAlignFixer.php:382]: Sorry, I meant a case with `@return static` (or maybe both).

Comment (HypeMC) [reply src/Fixer/Phpdoc/PhpdocAlignFixer.php:382]: Sorry, I'm not sure what you mean, the problem with `static bar(string $foo)` is that it's ambiguous, it could be a static method that returns `mixed` or a non static method that returns `static`. Since there is no way of knowing which one it is, we assume it's the latter. As for both, this case is covered by lines 1117-1120.

Comment (julienfalque) [reply src/Fixer/Phpdoc/PhpdocAlignFixer.php:382]: I would like to have a test case that shows the fixer behaves as expected when encountering a `@return static`. For example:
```diff
 /**
- * @param string $foo
+ * @param  string $foo
  * @return static
  **/
```

Comment (HypeMC) [reply src/Fixer/Phpdoc/PhpdocAlignFixer.php:382]: Done https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6366/commits/3274c1c44b5294353efafc747b003ceb899d8fc6

**Review by julienfalque — APPROVED** [review]
