### PR TITLE
fix: fix support call-site generic variance

### LINKED ISSUE #9248: Undefined array key "types"
### Problem description

After upgrading to v3.91.0 (from v3.90.0) I'm now facing these errors:

```
Files that were not fixed due to errors reported during fixing:
   1) /path/to/project/tests/Integration/Message/Handler/NewsfeedMessageHandlerTest.php

                                     
        [ErrorException]             
        Undefined array key "types"  
                                     

      PhpCsFixer\{closure}()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/DocBlock/TypeExpression.php at line 661
      PhpCsFixer\DocBlock\TypeExpression->parseCommaSeparatedInnerTypes()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/DocBlock/TypeExpression.php at line 542
      PhpCsFixer\DocBlock\TypeExpression->parse()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/DocBlock/TypeExpression.php at line 262
      PhpCsFixer\DocBlock\TypeExpression->__construct()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/DocBlock/Annotation.php at line 172
      PhpCsFixer\DocBlock\Annotation->getTypeExpression()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/AbstractPhpdocTypesFixer.php at line 75
      PhpCsFixer\AbstractPhpdocTypesFixer->fixType()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/AbstractPhpdocTypesFixer.php at line 54
      PhpCsFixer\AbstractPhpdocTypesFixer->applyFix()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php at line 56
      PhpCsFixer\AbstractFixer->fix()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 476
      PhpCsFixer\Runner\Runner->fixFile()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 403
      PhpCsFixer\Runner\Runner->fixSequential()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php at line 180
      PhpCsFixer\Runner\Runner->fix()
        in /path/to/project/tools/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php at line 423
      PhpCsFixer\Console\Command\FixCommand->execute()
        in /path/to/project/tools/vendor/symfony/console/Command/Command.php at line 326
      [ ... ]
```

This happens multiple times in my project. Looks like a generic type using a covariant fails parsing:

```php
/**
  * @return Collection<int, covariant BaseLinkItem>
  */
```

### Minimal reproducer CLI command

symfony php tools/vendor/bin/php-cs-fixer fix --diff --verbose

### Minimal reproducer code snippet

```php
<?php

namespace App\Entity\Traits;

use App\Entity\Link\Link;
use App\Entity\Super\BaseLinkItem;
use Doctrine\Common\Collections\Collection;

trait LinkItemsToLinksTrait
{
    /**
     * @return Collection<int, covariant BaseLinkItem>
     */
    abstract public function getLinkItems(): Collection;
}
```

### Fixer version

3.91.0

### PHP version

8.1.33

### How do you run Fixer?

Composer package

### Contribution Checks

- [x] I have verified if this problem was already reported
- [x] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### LINKED ISSUE #9249: php-cs-fixer crashes on nested generic types with call-site variance
### Problem description

PR #9212 added support for call-site variance (`covariant`/`contravariant` keywords) in generic types. However, the implementation only handles variance at the top level of type expressions, not within nested generics.

When a variance modifier appears inside a nested generic type (e.g., `Interface<covariant T>`), php-cs-fixer crashes with an `ErrorException: Undefined array key "types"` error.

This syntax **is valid** according to PHPStan's own phpdoc-parser implementation (see `GenericTypeNode::__toString()` which outputs variance modifiers inside angle brackets).

### Minimal reproducer CLI command

`./vendor/bin/php-cs-fixer fix --sequential -vvv test_variance_bug.php`

### Minimal reproducer code snippet

```php
<?php

/**
 * @template TEntity of object
 */
interface MetadataAwareInterface {}

/**
 * @template-covariant TEntity of object
 */
final readonly class TestClass
{
    /**
     * @param class-string<MetadataAwareInterface<TEntity>> $className
     */
    public function __construct(
        private string $className,
    ) {}

    /**
     * This causes a PHPStan variance error because the class template is covariant
     * but the interface template is invariant.
     *
     * @return class-string<MetadataAwareInterface<TEntity>>
     */
    public function getClassNameWorking(): string
    {
        return $this->className;
    }

    /**
     * This is the correct way to handle the variance issue - using call-site variance.
     * However, php-cs-fixer crashes with "Undefined array key 'types'" error.
     * This syntax is valid per PHPStan's phpdoc-parser (see GenericTypeNode::__toString()).
     *
     * @return class-string<MetadataAwareInterface<covariant TEntity>>
     */
    public function getClassNameBroken(): string
    {
        return $this->className;
    }
}
```

### Fixer version

3.91.0

### PHP version

8.4.13

### How do you run Fixer?

Composer package

### Contribution Checks

- [x] I have verified if this problem was already reported
- [x] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by kubawerlos**
fixes #9248
fixes #9249

### CODE REVIEW

**Comment by mvhirsch** [comment]
Thank you :heart:

**Comment by ker0x** [comment]
@kubawerlos Thank you for the quick fix!

File: src/DocBlock/TypeExpression.php [hunk 1]
```diff
@@ -54,6 +54,7 @@ final class TypeExpression
      * - and https://github.com/phpstan/phpdoc-parser/blob/1.26.0/src/Parser/PhpDocParser.php parser impl.
      */
     private const REGEX_TYPE = '(?<type>(?x) # single type
+            (?:co(ntra)?variant\h+)?
```
Comment (mvorisek) [inline src/DocBlock/TypeExpression.php:57]:
```suggestion
            (?:co(?:ntra)?variant\h+)?
```

no capturing group needed, the regex should not have any unnamed capturing group in general

Comment (keradus) [reply src/DocBlock/TypeExpression.php:57]: > no capturing group needed

👍🏻 

> the regex should not have any unnamed capturing group in general

can we somehow automate for code review? if you have idea, can you raise as PR proposal?

Comment (mvorisek) [reply src/DocBlock/TypeExpression.php:57]: It should be possible to evaluate the regex with dummy input and check if the captured indexes of string type matches the count of integer indexes + 1 (whole match).

Comment (keradus) [reply src/DocBlock/TypeExpression.php:57]: in such case, one has to provide this dummy input for each regex. i wonder if we can do it with static analysis without input data
