### PR TITLE
Fixer - resolve import conflict

### LINKED ISSUE #1698: Fixer class broken
Line 18 `use Symfony\Component\Finder\Finder;` won't work because of a conflict. I get:

```
PHP Fatal error:  Cannot use Symfony\Component\Finder\Finder as Finder because the name is already in use in /home/ubuntu/PHP-CS-Fixer/src/Fixer.php on line 18
```

No idea why travis hasn't picked this up!

### PR DESCRIPTION
**Pull request by keradus**
Closes #1698

cc @GrahamCampbell

### CODE REVIEW

File: Symfony/CS/Fixer.php [hunk 1]
```diff
@@ -13,7 +13,7 @@
 
 use SebastianBergmann\Diff\Differ;
 use Symfony\Component\EventDispatcher\EventDispatcher;
-use Symfony\Component\Finder\Finder;
+use Symfony\Component\Finder\Finder as SymfonyFinder;
 use Symfony\Component\Finder\SplFileInfo as FinderSplFileInfo;
```
Comment (GrahamCampbell) [inline Symfony/CS/Fixer.php]: Might make sense to alias this as SymfonySplFileInfo too @keradus?

Comment (keradus) [inline Symfony/CS/Fixer.php]: both ways are good for me, if you want send a PR and I will merge it ;)
