### PR TITLE
NoExtraBlankLinesFixer - handle cases on same line

### LINKED ISSUE #4867: Trait import bug
Non-idempotency of fixing imported traits can be observed as follows...

#### The PHP version you are using (`$ php -v`):
=> PHP 7.4.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> Latest 2.16 branch at time of writing (3849a14a804fa12271f08cdd3275e4183d30379b)

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

#### The configuration file you are using, if any:

These are the **minimal** rules to reproduce the issue:

```php
[
    "braces" => [
        "allow_single_line_closure" => true,
    ],
    "class_attributes_separation" => [
        "elements" => ["method"],
    ],
    "no_extra_blank_lines" => [
        "useTrait",
    ],
    "single_trait_insert_per_statement" => true,
    "space_after_semicolon" => true,
]
```

If I delete any one of these rules, then the issue does not occur!

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class Foo
{
    use Bar, Baz;

    public function baz()
    {
        //
    }
}

```

 * after **first run** of PHP CS Fixer:
```php
<?php

class Foo
{
    use Bar;
    use Baz;
    public function baz()
    {
        //
    }
}

```

 * after **second run** of PHP CS Fixer:
```php
<?php

class Foo
{
    use Bar;
    use Baz;

    public function baz()
    {
        //
    }
}

```

### PR DESCRIPTION
**Pull request by SpacePossum**
Fixes #4867

### CODE REVIEW

File: src/Fixer/Whitespace/NoExtraBlankLinesFixer.php [hunk 1]
```diff
@@ -370,7 +370,20 @@ private function removeBetweenUse($index)
...
 
         $nextUseCandidate = $this->tokens->getNextMeaningfulToken($next);
-        if (null === $nextUseCandidate || 1 === $nextUseCandidate - $next || !$this->tokens[$nextUseCandidate]->isGivenKind($this->tokens[$index]->getId())) {
+        if (null === $nextUseCandidate || !$this->tokens[$nextUseCandidate]->isGivenKind($this->tokens[$index]->getId())) {
+            return;
+        }
+
+        $isOnSameLine = true;
+        for ($i = $nextUseCandidate; $i > $index; --$i) {
+            if (false !== strpos($this->tokens[$i]->getContent(), "\n")) {
```
Comment (GrahamCampbell) [inline src/Fixer/Whitespace/NoExtraBlankLinesFixer.php]: Do we need to handle the case where there are only slash r characters for newlines?

Comment (SpacePossum) [reply src/Fixer/Whitespace/NoExtraBlankLinesFixer.php]: we could, so we should go for a regex solution using `\R`?

Comment (GrahamCampbell) [reply src/Fixer/Whitespace/NoExtraBlankLinesFixer.php]: I think so, yeh. There are probably some other places within the codebase that suffer this bug too. It might be worth adding a special method into the token class for testing for newline, to avoid this class of bug.

Comment (SpacePossum) [reply src/Fixer/Whitespace/NoExtraBlankLinesFixer.php]: I've updated to use regex, however I didn't find other case for now (did a quick check only though), so I get it within the class.
