### PR TITLE
switch_case_semicolon_to_colon should skip match/default statements

### LINKED ISSUE #5446: switch_case_semicolon_to_colon fixer breaks match expressions
## Bug report

PHP CS Fixer 2.18.0 on PHP 8.0.1

If I run PHP CS Fixer on a file containing a match expression, that file is listed under

```
Files that were not fixed due to errors reported during linting after fixing
```

In verbose mode, I get the following error message:

```
[PhpCsFixer\Linter\LintingException]                                              
Parse error: syntax error, unexpected token ":", expecting "," or ";" on line 7.

Applied fixers: switch_case_semicolon_to_colon
```

If I disable the mentioned `switch_case_semicolon_to_colon` fixer, the error is gone.

### Code snippet that reproduces the problem

```php
echo match (\PHP_MAJOR_VERSION) {
    8 => 'eight',
    9 => 'nine',
    default => 'unknown',
};
```

### PR DESCRIPTION
**Pull request by derrabus**
Fixes #5446.

### CODE REVIEW

File: src/Fixer/ControlStructure/SwitchCaseSemicolonToColonFixer.php [hunk 1]
```diff
@@ -110,4 +113,20 @@ protected function fixSwitchCase(Tokens $tokens, $index)
...
         }
     }
+
+    /**
+     * @param int $index
+     */
+    protected function fixSwitchDefault(Tokens $tokens, $index)
+    {
+        do {
+            if ($tokens[$index]->equalsAny([':', ';', [T_DOUBLE_ARROW]])) {
```
Comment (derrabus) [inline src/Fixer/ControlStructure/SwitchCaseSemicolonToColonFixer.php:123]: What puzzles me a bit: I would have expected that I could use `'=>'` instead of `[T_DOUBLE_ARROW]`, but that does not work. 🤔

Comment (keradus) [reply src/Fixer/ControlStructure/SwitchCaseSemicolonToColonFixer.php:123]: Yeah @derrabus ,it's tricky part of [tokenizer](https://www.php.net/manual/en/book.tokenizer.php) that is part of PHP itself.
sometimes, it returns an string, sometimes array with constant. actually `[T_DOUBLE_ARROW]` is shortcut for `[T_DOUBLE_ARROW, '=>']` (but as `T_DOUBLE_ARROW` can be represented only by `=>`, then the 2nd value can be skipped)

ref https://3v4l.org/2beJ3 , look for index 4 for `;` token

**Review by keradus — APPROVED** [review]
very nice, @derrabus

**Comment by keradus** [comment]
Thank you @derrabus.
