### PR TITLE
ClassAttributesSeparationFixer - Add `trait_import` support

### LINKED ISSUE #5490: class_attributes_separation doesn't consider trait usages
## Bug report

The rule `class_attributes_separation` doesn't consider trait `use` statements for blank line seperation.

   * PHP version: `7.4.12`
   * PHP CS Fixer version: `PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski`

### Code snippet that reproduces the problem

```php
class MyClass {
    use MyTrait;
    public const MY_VAR = 1;
    public functionmyFunction() { return true; }
}
```

### Expected

```php
class MyClass
{
    use MyTrait;

    public const MY_VAR = 1;

    public function myFunction()
    {
        return true;
    }
}
```

### Actual

```php
class MyClass
{
    use MyTrait;
    public const MY_VAR = 1;

    public function myFunction()
    {
        return true;
    }
}
```

Note that PHP CS Fixer won't remove the blank line if it's added manually.

### PR DESCRIPTION
**Pull request by SpacePossum**
closes #5490

### CODE REVIEW

**Review by kubawerlos — APPROVED** [review]

**Comment by keradus** [comment]
Thank you @SpacePossum.

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 1]
```diff
@@ -239,6 +240,7 @@ protected function createConfigurationDefinition()
                     'const' => self::SPACING_ONE,
                     'method' => self::SPACING_ONE,
                     'property' => self::SPACING_ONE,
+                    'trait_import' => self::SPACING_ONE,
```
Comment (kubawerlos) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:243]: @keradus @SpacePossum isn't this BC break? Now, after update to 3.0.1 everyone get the trait imports changed?

Comment (keradus) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:243]: I see that the initial decision was it's bugfix and going to 2.19.x

and yeah, each bugfix will change things for folks, thus can be considered BC breaker

Comment (kubawerlos) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:243]: Was it really a bugfix? I'ts not a problem to you or me as we know exactly what is going on in repo.

I'm thinking about people not familiar that well with the repo and seeing 3.0.1 patch version and wants the bugfixes.

Comment (SpacePossum) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:243]: No, it was intended for the rule to function this way but was never made to do so. If PHP adds another type of class element definition in the future it will be added to the list as well.
