### PR TITLE
DoctrineAnnotationIndentationFixer - Fix str_repeat() error

### LINKED ISSUE #3102: Exception in doctrine_annotation_indentation with multiline array
```
$ php -v
PHP 7.0.22-3 (cli) (built: Aug 23 2017 05:51:41) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-3, Copyright (c) 1999-2017, by Zend Technologies
```
```
$ php-cs-fixer -V
PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski (5642a36)
```

```php
<?php

class C
{
    /**
     * @A({
     *     @B()}
     * )
     */
    public $a;
}
```

That particular placement of the closing `}` in the annotation causes the following error:

```
$ php-cs-fixer fix -vvv --rules=doctrine_annotation_indentation cs_annot_ending_brace.php
Loaded config default.
Using cache file ".php_cs.cache".
E
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Checked all files in 0.003 seconds, 8.000 MB memory used

Files that were not fixed due to errors reported during fixing:
   1) /home/***/cs_annot_ending_brace.php


        [ErrorException]
        str_repeat(): Second argument has to be greater than or equal to 0


      {closure}()
      str_repeat()
        in phar:///home/***/local/bin/php-cs-fixer/src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php at line 107
      PhpCsFixer\Fixer\DoctrineAnnotation\DoctrineAnnotationIndentationFixer->fixAnnotations()
        in phar:///home/***/local/bin/php-cs-fixer/src/AbstractDoctrineAnnotationFixer.php at line 60
      PhpCsFixer\AbstractDoctrineAnnotationFixer->applyFix()
        in phar:///home/***/local/bin/php-cs-fixer/src/AbstractFixer.php at line 73
      PhpCsFixer\AbstractFixer->fix()
        in phar:///home/***/local/bin/php-cs-fixer/src/Runner/Runner.php at line 188
      PhpCsFixer\Runner\Runner->fixFile()
        in phar:///home/***/local/bin/php-cs-fixer/src/Runner/Runner.php at line 131
      PhpCsFixer\Runner\Runner->fix()
        in phar:///home/***/local/bin/php-cs-fixer/src/Console/Command/FixCommand.php at line 205
      PhpCsFixer\Console\Command\FixCommand->execute()
        in phar:///home/***/local/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php at line 264
      [ ... ]
```

Thanks.

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #3102.

@tsufeki Could you confirm that the fix works on your codebase please?

### CODE REVIEW

File: src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php [hunk 1]
```diff
@@ -72,7 +72,7 @@ protected function fixAnnotations(Tokens $tokens)
             if ($previousLineBracesDelta > 0) {
                 ++$indentLevel;
             }
-            if ($currentLineDelta < 0) {
+            if ($currentLineDelta < 0 && $indentLevel > 0) {
```
Comment (keradus) [inline src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php]: btw, why indent level was < 0 ?

**Comment by keradus** [comment]
other case is
```php
 /**
  * @Foo(x={
  *     @Bar
  * })
  * @Foo\z
  */', '
 /**
  * @Foo(x={
  * @Bar
  * })
  * @Foo\z
  */'),
```

so `@Bar` got indented. here, you drop indentation. why ?

File: src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php (hunk 1 above)
Comment (julienfalque) [reply src/Fixer/DoctrineAnnotation/DoctrineAnnotationIndentationFixer.php]: Because on line 2 we have `(` and `{` that create a new indent level, but we ignore one as they are on the same line to avoid indenting next line twice. On line 3 we have `}` that removes one level, and on line 4 we have `)` that removes one level again... -1 :)

**Comment by julienfalque** [comment]
When a line has "mixed content" (data + closing brace), the closing brace wins and one level of indentation is removed. On the test case you show, the line with `@Bar` only has data while on the new test case, the line with `@Bar` also contains a closing brace.

I added a new option on higher branch so that mixed lines remain indented instead.

**Comment by tsufeki** [comment]
Yes, this works for me, thank you.

**Comment by keradus** [comment]
Thanks for clarification @julienfalque

**Comment by keradus** [comment]
Thank you @julienfalque.
