### PR TITLE
fix: `NoUselessElseFixer` - handle conditional symbol declarations

### LINKED ISSUE #9340: `no_useless_else` and conditional class declaration
### Problem description

vide https://github.com/symfony/symfony/pull/62926#discussion_r2681215109

### PR DESCRIPTION
**Pull request by gharlan**
fixes #9340

### CODE REVIEW

File: src/Fixer/ControlStructure/NoUselessElseFixer.php [hunk 1]
```diff
@@ -70,7 +71,7 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
             }
 
             // clean up `else` if possible
-            if ($this->isSuperfluousElse($tokens, $index)) {
+            if ($this->isSuperfluousElse($tokens, $index) && !$this->containsNamedSymbolDeclaration($tokens, $index)) {
```
Comment (keradus) [inline src/Fixer/ControlStructure/NoUselessElseFixer.php:77]: please put a comment why we don't remove the `else` when symbol declared conditionally
