### PR TITLE
HeaderCommentFixer - do not remove class docs

### LINKED ISSUE #4067: HeaderComment - PHPDoc of class is removed
#### The PHP version you are using (`$ php -v`):
=> 7.2.8 (cli)

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.0

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix test.php

#### The configuration file you are using, if any:
```php
return PhpCsFixer\Config::create()
    ->setRules([
        'header_comment' => [
            'header' => 'header',
        ],
    ])
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

/**
 * Class A.
 */
class A
{
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

/*
 * header 
 */

class A
{
}

```

 * with the changes you expected instead:
```php
<?php

/*
 * header
 */

/**
 * Class A.
 */
class A
{
}

```

### PR DESCRIPTION
**Pull request by gharlan**
This PR tries to fix #4067.

It is difficult to find the correct/best behavior.

My proposal follows these rules:

1) A comment is a class doc comment, if it is a `T_DOC_COMMENT` (not a `T_COMMENT`) and if there is no blank line between the comment and the class/interface/trait/function:

```php
/**
 * this is a class doc comment
 * header comment will be added above
 */
class Foo {}

/**
 * this is NOT a class doc comment (blank line)
 * will be replaced by header comment
 */

class Foo {}

/*
 * this is NOT a class doc comment (no T_DOC_COMMENT)
 * will be replaced by header comment
 */
class Foo {}
```

2) If configuration for `separate` is `top` or `none`, the behavior does not change with this pr, because it is not possible then to make the decision by the blank line after the comment.

3) If `separate` is `both`/`bottom` and `comment_type` is `PHPDoc` and the comment looks like a class doc comment (see 1.), but the content is the same as the expected header, then it is considered as the header comment, and only the missing blank line is added.

### CODE REVIEW

File: src/Fixer/Comment/HeaderCommentFixer.php [hunk 1]
```diff
@@ -222,7 +222,29 @@ private function findHeaderCommentCurrentIndex(Tokens $tokens, $headerNewIndex)
     {
         $index = $tokens->getNextNonWhitespace($headerNewIndex);
 
-        return null === $index || !$tokens[$index]->isComment() ? null : $index;
+        if (null === $index || !$tokens[$index]->isComment()) {
+            return null;
+        }
+
+        $next = $index + 1;
```
Comment (kubawerlos) [inline src/Fixer/Comment/HeaderCommentFixer.php]: Isn't the convention here in the repo to name this `$nextIndex`?

Comment (gharlan) [reply src/Fixer/Comment/HeaderCommentFixer.php]: they both exist in many places. I don't know if there is a preferred one.

Comment (kubawerlos) [reply src/Fixer/Comment/HeaderCommentFixer.php]: Fair enough

**Comment by keradus** [comment]
Thank you @gharlan.
