### PR TITLE
fix: `PhpUnitAttributesFixer` - do not add for annotation `@testWith` when attribute `TestWith` already present

### LINKED ISSUE #9322: php_unit_attributes: testWith <> TestWithJson
### Problem description

`@testWith` gets annotation transformed into `TestWithJson` attribute even while `TestWith` already in-place

### Minimal reproducer CLI command

php-cs-fixer fix

### Minimal reproducer code snippet

```
+++ b/src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
@@ -347,6 +347,8 @@ abstract class HttpClientTestCase extends TestCase
      * @testWith [[]]
      *           [["Content-Length: 7"]]
      */
+    #[\PHPUnit\Framework\Attributes\TestWithJson('[[]]')]
+    #[\PHPUnit\Framework\Attributes\TestWithJson('[["Content-Length: 7"]]')]
     #[TestWith([[]])]
     #[TestWith([['Content-Length: 7']])]
     public function testRedirects(array $headers = [])
```

### Fixer version

newest

### PHP version

newest

### How do you run Fixer?

Composer package

### Contribution Checks

- [x] I have verified if this problem was already reported
- [x] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by kubawerlos**
fixes #9322

### CODE REVIEW

File: tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php [hunk 1]
```diff
@@ -780,6 +780,23 @@ class TheTest extends \PHPUnit\Framework\TestCase {}
...
+
+        yield 'do not add for annotation "@testWith" when attribute "TestWith" already present' => [
+            <<<'PHP'
+                <?php
+                class FooTest extends \PHPUnit\Framework\TestCase {
+                    /**
+                     * @testWith [1, 2]
+                     *           ["a", "b"]
+                     */
+                    #[\PHPUnit\Framework\Attributes\TestWith([1, 2])]
```
Comment (keradus) [inline tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php:792]: please add new test case with variant where attribute classess are imported:
```php
#[TestWith([1, 2])]
```

Comment (kubawerlos) [reply tests/Fixer/PhpUnit/PhpUnitAttributesFixerTest.php:792]: done
