### PR TITLE
PhpdocTagTypeFixer - must not remove inlined tags within other tags

### LINKED ISSUE #5815: `phpdoc_tag_type` destroys inline `{@see Foo}` annotations when used in `@internal` annotation
## Bug report

* PHP version: PHP 8.0.8 (cli) (built: Jul 12 2021 11:13:36) ( NTS )
* PHP CS Fixer version: PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
* the command used to run PHP CS Fixer (run with `-vvv`): vendor/bin/php-cs-fixer -vvv fix --dry-run --diff
* the configuration (file) you used
```php
<?php

$config = new PhpCsFixer\Config('foo');
$config->setRules(['phpdoc_tag_type' => true]);
$config->setUsingCache(false);

$config->getFinder()->in(__DIR__);

return $config;
```

### Code snippet that reproduces the problem

  ```php
<?php

namespace Bar;

use JsonSerializable;

/**
 * @internal Foo Bar {@see JsonSerializable}
 */ 
class Baz
{}
  ```

```
      ---------- begin diff ----------
--- /Users/max/bar/test.php
+++ /Users/max/bar/test.php
@@ -5,7 +5,7 @@
 use JsonSerializable;
 
 /**
- * @internal Foo Bar {@see JsonSerializable}
+ * @internal Foo Bar {@see JsonSerializable
  */ 
 class Baz
 {}

      ----------- end diff -----------
```

### PR DESCRIPTION
**Pull request by boesing**
Fixes #5815

### CODE REVIEW

File: tests/Fixer/Phpdoc/PhpdocTagTypeFixerTest.php [hunk 1]
```diff
@@ -348,6 +348,36 @@ public function provideFixCases()
                 '<?php
 /**
  * @return array{0: float, 1: int}
+ */',
```
Comment (julienfalque) [inline tests/Fixer/Phpdoc/PhpdocTagTypeFixerTest.php:351]: Could you add a case like the failing one you reported in #5815, i.e. `@internal ending with a {@see tag}`?

**Comment by boesing** [comment]
@juliendufresne yah, was thinking the same yesterday evening but was too tired. Added now, thanks for the reminder!

**Review by julienfalque — APPROVED** [review]

**Review by kubawerlos — APPROVED** [review]

**Comment by keradus** [comment]
Thank you @boesing.
