### PR TITLE
Fix transforming deprecations into exceptions

### LINKED ISSUE #5729: Too few arguments to function PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException
## Bug report

When I try to migrate my code, it crashes:

```ShellSession
$ PHP_CS_FIXER_FUTURE_MODE=1 php-cs-fixer fix -vvv
PHP CS Fixer 2.19.0 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.18
Loaded config default from "/home/jtojnar/Projects/guzzle-transcoder/.php-cs-fixer.php".
Using cache file ".php_cs.cache".

Fatal error: Uncaught ArgumentCountError: Too few arguments to function PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException::__construct(), 1 passed in /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/Utils.php on line 197 and at least 2 expected in /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/ConfigurationException/InvalidFixerConfigurationException.php:37
Stack trace:
#0 /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/Utils.php(197): PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException->__construct('To disable the ...')
#1 /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/RuleSet/RuleSet.php(57): PhpCsFixer\Utils::triggerDeprecation('To disable the ...', 'PhpCsFixer\\Conf...')
#2 /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php(671): PhpCsFixer\RuleSet\RuleSet->__construct(Array)
#3 /home/jtojnar/Projects/gu in /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/ConfigurationException/InvalidFixerConfigurationException.php on line 37
```

No error without future mode.

Looks like the `null` rule is the culprit:

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__);

$rules = [
    'yoda_style' => null,
];

$config = new PhpCsFixer\Config();

return $config
    ->setRules($rules)
    ->setFinder($finder);
```

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #5729.

### CODE REVIEW

File: src/Utils.php [hunk 1]
```diff
@@ -190,16 +190,19 @@ public static function naturalLanguageJoinWithBackticks(array $names)
...
      * Handle triggering deprecation error.
-     *
-     * @param string $message
-     * @param string $exceptionClass
      */
-    public static function triggerDeprecation($message, $exceptionClass = \RuntimeException::class)
+    public static function triggerDeprecation(\Exception $futureException)
     {
         if (getenv('PHP_CS_FIXER_FUTURE_MODE')) {
-            throw new $exceptionClass("{$message} This check was performed as `PHP_CS_FIXER_FUTURE_MODE` env var is set.");
```
Comment (keradus) [inline src/Utils.php:200]: TLDR - this was not working for `InvalidFixerConfigurationException` which has a constructor prototype of `$name, $description` and not `$description` only

**Review by keradus — APPROVED** [review]

**Review by kubawerlos — APPROVED** [review]

**Comment by SpacePossum** [comment]
Thank you @julienfalque.
