### PR TITLE
IncludeFixer - fix incorrect order of fixing

### LINKED ISSUE #3463: include fixer doesn't fix correctly when using include_once/require_once and include/require
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.10.0

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix --rules=include test.php

#### The configuration file you are using, if any:
N/A

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
require_once('test1.php');
include_once('test2.php');
require('test3.php');
include('test4.php');
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
require_once 'test1.php';
include_once 'test2.php'; require('test3.php');
 include('test4.php');
```

 * with the changes you expected instead:
```php
<?php
require_once 'test1.php';
include_once 'test2.php';
require 'test3.php';
include 'test4.php';

```

### PR DESCRIPTION
**Pull request by kubawerlos**
Lines 65, 129, 133 and 134 are the actual fix - other changes are small cleanup while I was trying to understand the fixer.

closes #3463

### CODE REVIEW

File: src/Fixer/ControlStructure/IncludeFixer.php [hunk 1]
```diff
@@ -80,20 +82,12 @@ private function clearIncludies(Tokens $tokens, array $includies)
                     $this->removeWhitespaceAroundIfPossible($tokens, $braces['close']);
                     $tokens->clearTokenAndMergeSurroundingWhitespace($braces['open']);
                     $tokens->clearTokenAndMergeSurroundingWhitespace($braces['close']);
-
-                    $nextSiblingIndex = $tokens->getNonEmptySibling($includy['begin'], 1);
-                    if (!$tokens[$nextSiblingIndex]->isWhitespace()) {
-                        $tokens->insertAt($nextSiblingIndex, new Token(array(T_WHITESPACE, ' ')));
+                    if (!$tokens[$nextIndex]->isWhitespace()) {
```
Comment (SpacePossum) [inline src/Fixer/ControlStructure/IncludeFixer.php]: without this statement the test pass as well, which seems OK because line 91 repeats the same check and performs the same insert of the whitespace, is this something that could simplified?

**Comment by SpacePossum** [comment]
thanks for picking this up @kubawerlos :+1:

**Comment by SpacePossum** [comment]
The clearing/removing of the tokens happens in an unsave way, which causes issues.
For example, when a spacing token contains a linebreak is removed (or replaced with spacing without a linebreak) the next line might get append to a comment.
For example:
```
# a
echo 1;
```
becomes
```
# a echo 1;
```

I've added a test to prove the issue; removing `#6`, `#5` and `#4` from there in any order show additional fail cases.

**Comment by keradus** [comment]
#3496 got merged, please rebase @kubawerlos

**Comment by kubawerlos** [comment]
@keradus rebased

**Comment by keradus** [comment]
Thank you @kubawerlos.
