### PR TITLE
GroupImportFixer severely broken

### LINKED ISSUE #5408: GroupImportFixer severely broken
## Bug report

I experienced some major issues with the new GroupImportFixer.  It's throwing a parse error on some generated code and severely mangling the output diff.  It looks like it's nesting some group statements, eating the class name itself ("TestClassSoftDeletesuse"), inventing a "D" namespace, etc.  This is from a small small testcase I extracted from a much larger class to demonstrate the issue.  It was also conflicting with the OrderedImportsFixer so I ran it with only the GroupImportFixer, but that is likely a secondary issue.

### Code snippet that reproduces the problem

Test case:
```php
<?php

namespace App\Models;

use App\Models\Traits\JsonObjects;
use App\Services\AccountService;
use App\Services\LocationService;
use DateTime;
use DateTimeZone;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\JoinClause;
use Illuminate\Notifications\Notifiable;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class TestClass
{
    use Notifiable;
    use SoftDeletes;
}
```

Output:
```
❯ php-cs-fixer fix -vvv --using-cache=no --dry-run --diff --rules=group_import app/Models/TestClass.php
PHP CS Fixer 2.17.3 Desert Beast by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.13
Loaded config default.
E
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Checked all files in 0.007 seconds, 20.000 MB memory used

Files that were not fixed due to errors reported during linting after fixing:
   1) app/Models/TestClass.php

                                                                                                 
        [PhpCsFixer\Linter\LintingException]                                                     
        Parse error: syntax error, unexpected 'Illuminate' (T_STRING), expecting '}' on line 9.  
                                                                                                 

      Applied fixers: group_import
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 
 namespace App\Models;
 
 use App\Models\Traits\JsonObjects;
-use App\Services\AccountService;
-use App\Services\LocationService;
-use DateTime;
-use DateTimeZone;
-use Illuminate\Database\Eloquent\Model;
-use Illuminate\Database\Eloquent\Relations\BelongsTo;
-use Illuminate\Database\Eloquent\Relations\HasOne;
-use Illuminate\Database\Eloquent\SoftDeletes;
 use Illuminate\Database\Query\JoinClause;
-use Illuminate\Notifications\Notifiable;
-use Illuminate\Notifications\Notification;
-use Illuminate\Support\Arr;
-use Illuminate\Support\Collection;
-use Illuminate\Support\Facades\DB;
-use Illuminate\Support\Facades\Log;
-
-class TestClass
-{
-    use Notifiable;
+use App\Services\{AccountService, LocationService};
+use D\{DateTime, DateTimeZone};
+use Illuminate\Database\Eloquent\{classModeluse Illuminate\Database\Eloquent\Relations\{ BelongsTo, HasOne};
+use Illuminate\Database\Eloquent\{TestClassSoftDeletesuse Illuminate\Notifications\{
+Notifiable, Notification};
+use Illuminate\Support\{{Arr, Collection};
+use Illuminate\Support\Facades\{
+    DB, Log};
+use Notifiable;
     use SoftDeletes;
 }
 

      ----------- end diff -----------
```

### PR DESCRIPTION
**Pull request by Leprechaunz**
Fixes #5408

### CODE REVIEW

File: tests/Fixer/Import/GroupImportFixerTest.php [hunk 1]
```diff
@@ -247,6 +247,31 @@ public function provideFixCases()
...
+use Framework\Database\ORM\Relations\HasOne;
+use Framework\Database\ORM\SoftDeletes;
+use Framework\Database\Query\JoinClause;
+use Framework\Notifications\Notifiable;
+use Framework\Notifications\Notification;
+use Framework\Support\Arr;
+use Framework\Support\Collection;
+use Framework\Support\Facades\DB;
+use Framework\Support\Facades\Log;
 ',
```
Comment (kubawerlos) [inline tests/Fixer/Import/GroupImportFixerTest.php:275]: Let'a add a test with multiple namespaces with the same length, with input data like:
```php
<?php
use Framework\Foo\Class1;
use Framework\Foo\Class2;
use Framework\Bar\Class3;
use Framework\Bar\Class4;
use Framework\Bar\Class5;
use Framework\Baz\Class6;
use Framework\Foo\Class7;
```

**Review by kubawerlos — CHANGES_REQUESTED** [review]

**Review by kubawerlos — APPROVED** [review]
Cool 👍🏼

**Comment by keradus** [comment]
Thank you @Leprechaunz.
