### PR TITLE
bug: [BinaryOperatorFixer] Fix more issues with scoped operators

### LINKED ISSUE #6551: New issues in `binary_operator_spaces` after latest master `32cf09e`
## Bug report

PHP-CS-Fixer v3.9.6-DEV (`32cf09e`)
PHP v8.1.9
Configuration:
```
'binary_operator_spaces' => [
    'default'   => 'single_space',
    'operators' => [
        '='  => 'align_single_space_minimal',
        '=>' => 'align_single_space_minimal',
        '||' => 'align_single_space_minimal',
        '.=' => 'align_single_space_minimal',
    ],
],
```

### Code snippet that reproduces the problem

1. Anonymous function and array in lambda body
```diff
         return array_map(fn ($fieldIndex) => (object) [
-            'name'       => oci_field_name($this->resultID, $fieldIndex),
-            'type'       => oci_field_type($this->resultID, $fieldIndex),
+            'name' => oci_field_name($this->resultID, $fieldIndex),
+            'type' => oci_field_type($this->resultID, $fieldIndex),
             'max_length' => oci_field_size($this->resultID, $fieldIndex),
         ], range(1, $this->getFieldCount()));

        $this->query = $this->db->prepare(static fn ($db) => $db->table('user')->insert([
-            'name'    => 'a',
-            'email'   => 'b@example.com',
+            'name' => 'a',
+            'email' => 'b@example.com',
             'country' => 'JP',
         ]));
```

2. Foreach in foreach
```diff
         $output = [];

-        foreach ($data as $name => $array) {
+        foreach ($data as $name       => $array) {
             foreach ($array as $field => $value) {
                 $pointer = &$output[$name];
```

3. Foreach with yield
```diff
         foreach ($cases as $type => $case) {
-            yield $type => $case;
+            yield $type          => $case;
         }
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes #6551

cc @julienfalque

### CODE REVIEW

File: src/Fixer/Operator/BinaryOperatorSpacesFixer.php [hunk 1]
```diff
@@ -695,6 +701,22 @@ private function injectAlignmentPlaceholdersForArrow(Tokens $tokens, int $startA
...
+
+            if ($token->equals('{')) {
+                $until = $tokens->findBlockEnd(Tokens::BLOCK_TYPE_CURLY_BRACE, $index);
+                $this->injectArrayAlignmentPlaceholders($tokens, $index + 1, $until - 1);
+                $index = $until;
+
+                continue;
+            }
+
+            if ($token->equals('(')) {
```
Comment (VincentLanglet) [inline src/Fixer/Operator/BinaryOperatorSpacesFixer.php:713]: Since I stopped to ignore the if/foreach/... skip, I need to add a check to create a new scope every time a (, or a { is open.

This way the two `=>` are not considered in the same scope.
```
foreach ($a => $b) {
    foreach ($c => $d) {
}}
```

This strategy was already used for the alignement of all the others operators.

**Review by julienfalque — APPROVED** [review]

**Comment by julienfalque** [comment]
Thank you @VincentLanglet.
