### PR TITLE
ArrayIndentationFixer - Fix indentation after trailing spaces

### LINKED ISSUE #4290: array_indentation is wrong in nested short array creation
PHP CS Fixer indents the nested short array creation twice, with closing bracket indented also. This happens only in one file (form validation config) and in one array creation.

#### The PHP version:
PHP 5.6.40-1+ubuntu18.04.1+deb.sury.org+1 (cli)

#### Framework:
CodeIgniter 3.1.7

#### PHP CS Fixer version:
2.14.0

#### The command to run PHP CS Fixer:
php-cs-fixer fix
installed with composer (global)

#### The configuration file:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('assets')
    ->exclude('img')
    ->exclude('system')
    ->exclude('application/cache')
    ->exclude('application/logs')
    ->exclude('application/vendor')
    ->exclude('application/views')
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'array_syntax' => ['syntax' => 'short'],
        'logical_operators' => true,
        'align_multiline_comment' => ['comment_type' => 'phpdocs_only'],
        'array_indentation' => true
    ])
    ->setRiskyAllowed(true)
    ->setFinder($finder)
;
```

#### Samples of PHP code:
 * before running PHP CS Fixer (no changes):
```php
$config['change_pass'] = [
    [
        'field' => 'password',
        'label' => 'password',
        'rules' => 'required|min_length[4]'
    ],
    [
        'field' => 'password2',
        'label' => 'Confirm password',
        'rules' => 'required|matches[password]'
    ],
];
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
$config['change_pass'] = [
        [
            'field' => 'password',
            'label' => 'password',
            'rules' => 'required|min_length[4]'
        ],
        [
            'field' => 'password2',
            'label' => 'Confirm password',
            'rules' => 'required|matches[password]'
        ],
    ];
```

 * with the changes expected instead:
(No changes)

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #4290.

### CODE REVIEW

File: src/Fixer/Whitespace/ArrayIndentationFixer.php [hunk 1]
```diff
@@ -300,7 +300,7 @@ private function getLineIndentation(Tokens $tokens, $index)
 
     private function extractIndent($content)
     {
-        if (Preg::match('/\R([\t ]*)[^\r\n]*$/', $content, $matches)) {
+        if (Preg::match('/\R([\t ]*)[^\r\n]*$/D', $content, $matches)) {
```
Comment (keradus) [inline src/Fixer/Whitespace/ArrayIndentationFixer.php]: let me merge this anyway, as we have nice utests for the fixer, but...
i'm not big fan of non-PCRE modifiers

**Comment by keradus** [comment]
Thank you @julienfalque.
