### PR TITLE
ArgumentsAnalyzer - support PHP8.1 readonly

### LINKED ISSUE #6221: nullable_type_declaration_for_default_null_value fails for nullable readonly parameter in promoted constructor
I think `NullableTypeDeclarationForDefaultNullValueFixer` crashes when I'm trying to add `readonly` modifier to nullable parameter in promoted constructor. 

## Bug report
   * PHP version: PHP 8.1.0 (cli) (built: Nov 30 2021 07:26:16) (NTS)
   * PHP CS Fixer version: PHP CS Fixer 3.4.0 Si! by Fabien Potencier and Dariusz Ruminski
   * the command used to run PHP CS Fixer (run with `-vvv`):
```
PHP CS Fixer 3.4.0 Si! by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.1.0
Loaded config default.
Using cache file ".php-cs-fixer.cache".
E                                                                                                                                                                                                                                                                                                           1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 0.004 seconds, 12.000 MB memory used

Files that were not fixed due to errors reported during linting after fixing:
   1) /application/src/ReadonlyThing.php

                                                                            
        [PhpCsFixer\Linter\LintingException]                                
        Parse error: syntax error, unexpected token "readonly" on line 11.  
                                                                            

      Applied fixers: nullable_type_declaration_for_default_null_value
ERROR: 64
```
   * the configuration (file) you used: none


### Code snippet that reproduces the problem
```php
<?php

class ReadonlyThing
{
    public function __construct(
        protected readonly bool $nullable = null,
    ) {
    }
}
```

### Expected output
```php
<?php

class ReadonlyThing
{
    public function __construct(
        protected readonly ?bool $nullable = null,
    ) {
    }
}
```

Btw. when it's used with easy-coding-standard, it's even worse:
```php
<?php

class ReadonlyThing
{
    public function __construct(
        protected ?readonly ?bool $nullable = null,
    ) {
    }
}
```

### PR DESCRIPTION
**Pull request by SpacePossum**
closes #6221

### CODE REVIEW

File: tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php [hunk 1]
```diff
@@ -500,4 +500,27 @@ function foo2(?string &/*comment*/$param2 = null) {}
...
+    /**
+     * @dataProvider provideFix82Cases
+     * @requires PHP 8.1
+     */
+    public function testFix81(string $expected): void
+    {
+        $this->doTest($expected);
+    }
+
+    public function provideFix82Cases(): iterable
```
Comment (jrmajor) [inline tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php:513]:
```suggestion
    public function provideFix81Cases(): iterable
```

Comment (SpacePossum) [reply tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php:513]: :+1:  thanks, done, also update the PHPDoc for the provider

File: src/Tokenizer/Analyzer/ArgumentsAnalyzer.php [hunk 2]
```diff
@@ -87,6 +87,16 @@ public function getArguments(Tokens $tokens, int $openParenthesis, int $closePar
 
     public function getArgumentInfo(Tokens $tokens, int $argumentStart, int $argumentEnd): ArgumentAnalysis
     {
+        static $skipTypes = null;
+
+        if (null === $skipTypes) {
+            $skipTypes = [T_ELLIPSIS, CT::T_CONSTRUCTOR_PROPERTY_PROMOTION_PUBLIC, CT::T_CONSTRUCTOR_PROPERTY_PROMOTION_PROTECTED, CT::T_CONSTRUCTOR_PROPERTY_PROMOTION_PRIVATE];
+
+            if (\defined('T_READONLY')) { // @TODO: drop condition when PHP 8.1+ is required
```
Comment (krzysztofrewak) [inline src/Tokenizer/Analyzer/ArgumentsAnalyzer.php:95]: In `src/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixer.php` you're checking `if (\PHP_VERSION_ID >= 70400)` and here there's only a check for defined keyword. I'm just curious if you'd have any standard for situations like this?

Maybe the one below would be easier to find in the future with required PHP 8.1?
```suggestion
            if (\PHP_VERSION_ID >= 80100) {
```

Comment (SpacePossum) [reply src/Tokenizer/Analyzer/ArgumentsAnalyzer.php:95]: I think the `defined` is maybe more correct here, as that is what we care about at this point in the code, however since PHP never adds new tokens in patches doing a version check would be effectively the same. 
The version check is a bit cheaper IIRC so that is probably why it was used in the other part of the fixer.

Comment (krzysztofrewak) [reply src/Tokenizer/Analyzer/ArgumentsAnalyzer.php:95]: Thanks for this explanation. Have a nice day!

Comment (SpacePossum) [reply src/Tokenizer/Analyzer/ArgumentsAnalyzer.php:95]: thanks for review :)  and have a great day as well!

**Review by kubawerlos — APPROVED** [review]

**Review by GrahamCampbell — APPROVED** [review]

**Review by krzysztofrewak — APPROVED** [review]
