### PR TITLE
SingleSpaceAfterConstructFixer - better handling of closing parenthesis and brace

### LINKED ISSUE #5448: Extra space added after comments inlined in function calls
With the latest version of php-cs-fixer, when parsing e.g. `src/Symfony/Component/Console/Tests/DependencyInjection/AddConsoleCommandPassTest.php`:

image

This suggested change is wrong of course.

### PR DESCRIPTION
**Pull request by keradus**
closes #5448

### CODE REVIEW

File: tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php [hunk 1]
```diff
@@ -3170,6 +3170,15 @@ public function provideCommentsCases()
...
 $a = 4; /** 4 */
 echo 1;
+',
+        ];
+
+        yield 'exceptions' => [
+            '<?php
+new Dummy(/* a */);
+new Dummy(/** b */);
+foo(/* c */);
```
Comment (mvorisek) [inline tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php:3180]: what about `foo('x'/* c */, 'y');` ?

I think it still enforces space after `*/` which is againt every convention

Comment (mvorisek) [reply tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php:3180]: also for block comment before `->`, see https://github.com/atk4/data/pull/827/files#diff-1b13a61af17b481a4e15159a87f2a89937836e504284460f2164bfafc1d32348R83
