### PR TITLE
FullyQualifiedStrictTypesFixer - Fix the short type detection when a question mark (nullable) is prefixing it.

### LINKED ISSUE #4302: Fix FullyQualifiedStrictTypesFixer when return types starts with ?
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=>7.1.26

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.14

#### The configuration file you are using, if any:
When using the directive `fully_qualified_strict_types`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

declare(strict_types = 1);

namespace Bar\Boo;

class Foo {
  public function random(): ?/Bar/Foo/Int {
    // Returns an instance of /Bar/Foo/Int or Null.
  }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
// Nothing changes.
```

 * with the changes you expected instead:
```php
<?php

declare(strict_types = 1);

namespace Bar\Boo;

use Bar\Foo\Int;

class Foo {
  public function random(): ?Int {
    // Returns an instance of /Bar/Foo/Int or Null.
  }
}
```

### PR DESCRIPTION
**Pull request by drupol**
Fix #4302

### CODE REVIEW

File: src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php [hunk 1]
```diff
@@ -76,7 +76,9 @@ public function __construct($name, $startIndex, $endIndex)
      */
     public function getName()
     {
-        return $this->name;
+        return $this->isNullable() ?
```
Comment (keradus) [inline src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php]: do it once, in constructor

Comment (drupol) [reply src/Tokenizer/Analyzer/Analysis/TypeAnalysis.php]: Fixed.

**Comment by drupol** [comment]
Here's the patch for branch 2.14: https://gist.github.com/drupol/c43a4ba8712782e104194fdc015c8ede
We need it for our project.

**Comment by keradus** [comment]
thanks for the patch @drupol .
yet, to not waste your time on it, if you send a PR against older branch, after PR would be merged, that branch would also be merged into higher branch - and usually git does that without conflicts, and for small conflicts I resolve them myself.
it's very rare that for same change we ask original author to prepare independent patches for different branches - it's only in case of super complex change - in other words, don't prepare the "other branch patches" except if you was explicitly asked for ;)

**Comment by drupol** [comment]
Allrigthty!

Thanks.

File: tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php [hunk 2]
```diff
@@ -36,6 +36,19 @@ public function testCodeWithReturnTypes($expected, $input = null)
         $this->doTest($expected, $input);
     }
 
+    /**
+     * @requires PHP 7.1
+     *
+     * @dataProvider provideCodeWithReturnTypesCasesWithNullableCases
+     *
+     * @param mixed      $expected
```
Comment (kubawerlos) [inline tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php]: ~~Can we have `string` here, and in the line below, instead of `mixed`?~~
Actually, can we have `string` instead of `mixed` in the whole file?

Comment (drupol) [reply tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php]: I think yes.

Comment (SpacePossum) [reply tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php]: done

**Comment by SpacePossum** [comment]
Thank you @drupol.

**Comment by drupol** [comment]
Thanks ! Very needed here :)
