### PR TITLE
ClassAttributesSeparationFixer - Introduce `only_if_meta` spacing option

### LINKED ISSUE #4014: ClassAttributesSeparationFixer - Option to add blank lines only before items with PHPDocs
I'd like to have a new option for `class_attributes_separation` rule that makes it add blank lines before items with PHPDocs only, e.g.:

```diff
 class Foo
 {
     private $foo;
     private $bar;
 }
 
 class Bar
 {
     /**
      * @var int
      */
     private $foo;
+
     /**
      * @var int
      */
     private $bar;
 }
```
instead of:
```diff
 class Foo
 {
     private $foo;
+
     private $bar;
 }
 
 class Bar
 {
     /**
      * @var int
      */
     private $foo;
+
     /**
      * @var int
      */
     private $bar;
 }
```

Maybe the format of this option should mimic the format of option `elements` as one might not want to enable the new behavior for all kinds of element. I would make it default to constants and properties.

WDYT?

### LINKED ISSUE #5701: ClassAttributesSeparationFixer - ['const' => 'none'] removing unexpected whitespaces if including docblocks
## Bug report

PHP version:
```
PHP 8.0.5 (cli) (built: Apr 28 2021 00:30:18) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

PHP-CS-Fixer version:
```
PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
```

Command used:
```
vendor/bin/php-cs-fixer fix -v
```

Relevant configuration:
```
'class_attributes_separation' => [
    'elements' => [
        'const' => 'none',
        'method' => 'one',
        'property' => 'one',
    ],
],
```

### Code snippet that reproduces the problem

case 1:
```diff
 class Foo
 {
     public const BAR = 1;
-
     public const BAZ = 2;

     public static function getX()
     {
         return 'X';
     }
 }
```
Change here is totally expected.

case 2:
```diff
 class Foo
 {
     /** @var int */
     public const BAR = 1;
-
     /** @var int */
     public const BAZ = 2;
-
     /**
      * Defaults
      *
      * @var array<int, string>
      */
     protected array $defaults = [];

     public static function getX()
     {
         return 'X';
     }
 }
```

For case 2, if the const has a doc block, it still strips the whitespaces around it. Then, when the last const is followed by a property with a docblock, the whitespace below the const is also removed.

### PR DESCRIPTION
**Pull request by paulbalandan**
Closes #4014 .

This PR introduces a new spacing option `only_if_meta` to `class_attributes_separation` fixer. The behavior of this option is technically the same with `none` except that when there is a `T_DOC_COMMENT` or `T_ATTRIBUTE` (or both) above the class element the option will now behave as `one`.

**Examples:**

`['elements' => ['const' => 'only_if_meta']]`
```php
// Before
class Sample
{
    /** @var int */
    const FOO = 1;
    /** @var int */
    const BAR = 2;
    #[Foo\Baz]
    const BAZ = 3;
    const OTHER = 4;
}

// After
class Sample
{
    /** @var int */
    const FOO = 1;

    /** @var int */
    const BAR = 2;

    #[Foo\Baz]
    const BAZ = 3;
    const OTHER = 4;
}
```

`['elements' => ['property' => 'only_if_meta']]`
```php
// Before
class Sample
{
    public $a;
    public $b;
    /** @var string */
    public $c;
}

// After
class Sample
{
    public $a;
    public $b;

    /** @var string */
    public $c;
}
```

### CODE REVIEW

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 1]
```diff
@@ -39,6 +39,11 @@
  */
 final class ClassAttributesSeparationFixer extends AbstractFixer implements ConfigurableFixerInterface, WhitespacesAwareFixerInterface
 {
+    /**
+     * @internal
+     */
+    public const SPACING_HYBRID = 'hybrid';
```
Comment (julienfalque) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:45]: `hybrid` is not very explicit about what it does: I suggest `one_if_phpdoc`.

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 2]
```diff
@@ -355,7 +383,39 @@ private function fixSpaceAboveClassElement(Tokens $tokens, int $classStartIndex,
...
+        // start or end of the class and no additional line breaks are needed
+        if ($notWhiteIndex === $classStartOrEndIndex) {
+            return 1;
+        }
+
+        $lineCount = 2;
+
+        // initially, `hybrid` and `none` behaves the same
+        if (\in_array($spacing, [self::SPACING_HYBRID, self::SPACING_NONE], true)) {
+            $lineCount = 1;
```
Comment (julienfalque) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:410]: We can use early returns instead of a variable to improve readability:
```
if (/* ... */) {
    return 1;
}
```
This would require to change the `if`s order though.

File: tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php [hunk 3]
```diff
@@ -1144,6 +1144,179 @@ public function f2() {}
...
+                    }
+                ',
+                '<?php
+                    class A
+                    {
+                        const FOO = 1;
+
+                        const BAR = 2;
+
+                        /** @var int */
```
Comment (julienfalque) [inline tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php:1168]: All the new test cases show empty lines are removed when there is no PHPDoc, but they don't show empty lines are added when there is a PHPDoc as all input already has these empty lines. I would remove those from input samples.

**Review by julienfalque — COMMENTED** [review]
Nice :+1:

File: tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php [hunk 4]
```diff
@@ -1144,6 +1144,179 @@ public function f2() {}
...
+                {
+                    /**
+                     * @ORM\Column(name="one", type="text")
+                     */
+                    private string $one;
+
+                    /**
+                     * @ORM\Column(name="two", type="text")
+                     */
+                    private string $two;
```
Comment (julienfalque) [inline tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php:1240]: Those tests are failing on PHP ≤ 7.3 because they use typed properties. They should be moved to `provideFix74Cases()`.

File: tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php [hunk 5]
```diff
@@ -1281,15 +1410,16 @@ class Foo {
...
-                var ? Foo\Bar $qux;
+                var ?Foo\Bar $qux;
             }',
             '<?php
             class Foo {
                 private ?int $foo;
                 protected string $bar;
                 public iterable $baz;
-                var ? Foo\Bar $qux;
+                var ?Foo\Bar $qux;
```
Comment (julienfalque) [inline tests/Fixer/ClassNotation/ClassAttributesSeparationFixerTest.php:1420]: Changing this test case is not required, please revert.

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php (hunk 1 above)
Comment (kubawerlos) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php]: I had the same remark, but could not find a good name, kudos @julienfalque for finding it.

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 6]
```diff
@@ -49,7 +49,16 @@ final class ClassAttributesSeparationFixer extends AbstractFixer implements Conf
      */
     public const SPACING_ONE = 'one';
 
-    private const SUPPORTED_SPACINGS = [self::SPACING_NONE, self::SPACING_ONE];
+    /**
+     * @internal
+     */
+    public const SPACING_ONE_IF_PHPDOC = 'one_if_phpdoc';
```
Comment (kubawerlos) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:55]: I'm not sure changing `private` to `public` only to use it in tests is a way to go. IMHO using literal strings in tests is perfectly fine.

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 7]
```diff
@@ -185,7 +210,7 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
     protected function createConfigurationDefinition(): FixerConfigurationResolverInterface
     {
         return new FixerConfigurationResolver([
-            (new FixerOptionBuilder('elements', 'Dictionary of `const|method|property` => `none|one` values.'))
+            (new FixerOptionBuilder('elements', 'Dictionary of `const|method|property` => `none|one|one_if_phpdoc` values.'))
```
Comment (kubawerlos) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:213]: Can we have this string generated from constants? Both `const|method|property` and `none|one|one_if_phpdoc`.

**Review by kubawerlos — CHANGES_REQUESTED** [review]

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php (hunk 6 above)
Comment (paulbalandan) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:55]: @kubawerlos I'm not sure I followed what you want me to do here. Should I change all of the spacing constants here to `private`, then use the literal strings in the tests?

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php (hunk 7 above)
Comment (paulbalandan) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php]: Done

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php (hunk 6 above)
Comment (julienfalque) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:55]: There is no private to public change here though I agree with @kubawerlos: we should use literal strings in tests rather than the constant. Otherwise, we might change the constant and thus introduce a BC break without the test detecting it. Can you make these constants private please?

Comment (paulbalandan) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php]: Done

**Review by julienfalque — APPROVED** [review]

**Review by SpacePossum — APPROVED** [review]

**Comment by ruudk** [comment]
🙌  Amazing! Thanks for tackling this @paulbalandan 

I [tried this in the past](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5060) but couldn't get it to work. 

Instead of calling the option `one_if_phpdoc` shouldn't we also think about PHP 8 Attributes? How do we want to support that in the future? Maybe the option should be called `one_if_phpdoc_or_attribute` and support Attributes as well?

Because properties can be annotated with only an attribute, with an attribute and phpdoc, only a phpdoc, or nothing at all.

**Comment by julienfalque** [comment]
@ruudk Good point! I agree PHP 8 attributes should be supported. Maybe a name like `only_if_meta` would be more appropriate? Anyway, @paulbalandan, could you please make the changes for that?

**Comment by paulbalandan** [comment]
@julienfalque sure, I'll look into that. Just to confirm, `meta` means phpdocs and attributes only, right?

**Comment by julienfalque** [comment]
Thanks! Yep, `meta` means "PHPDocs or attritbute".

**Comment by ruudk** [comment]
Does it matter if it's a phpdoc or regular comment? I think as a user you expect the same behavior:

```
    const FOO = 1;
    
    // Some comment to explain more
    const BAR = 2;
    const BAZ = 3;
```
?

**Comment by julienfalque** [comment]
IMO we can start with PHPDocs and attributes only and see if the option needs adjustements afterwards.

**Comment by ruudk** [comment]
I was looking at the example in the OP:
```php

// Before
class Sample
{
    /** @var int */
    const FOO = 1;
    /** @var int */
    const BAR = 2;
    #[Foo\Baz]
    const BAZ = 3;
    const OTHER = 4;
}

// After
class Sample
{
    /** @var int */
    const FOO = 1;

    /** @var int */
    const BAR = 2;

    #[Foo\Baz]
    const BAZ = 3;
    const OTHER = 4;
}
```

Shouldn't there also be a newline between `BAZ` and `OTHER` because `BAZ` has meta? That's how I would manually format this.

Like this:
```php

// Before
class Sample
{
    /** @var int */
    const FOO = 1;
    /** @var int */
    const BAR = 2;
    #[Foo\Baz]
    const BAZ = 3;
    const OTHER = 4;
}

// After
class Sample
{
    /** @var int */
    const FOO = 1;

    /** @var int */
    const BAR = 2;

    #[Foo\Baz]
    const BAZ = 3;

    const OTHER = 4;
}
```

**Comment by paulbalandan** [comment]
The rule adds a new line if the element _itself_ has a meta above it. It will not be affected if the element above it has the meta instead.

**Review by kubawerlos — APPROVED** [review]

**Comment by SpacePossum** [comment]
closes #5800 as well

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 8]
```diff
@@ -346,16 +418,53 @@ private function fixSpaceAboveClassElement(Tokens $tokens, int $classStartIndex,
...
-        $this->correctLineBreaks($tokens, $nonWhiteAbove, $firstElementAttributeIndex, $nonWhiteAbove === $classStartIndex || self::SPACING_NONE === $spacing ? 1 : 2);
+        $reqLineCount = $this->determineRequiredLineCount($tokens, $nonWhiteAbove, $classStartIndex, $spacing);
+
+        $this->correctLineBreaks($tokens, $nonWhiteAbove, $firstElementAttributeIndex, $reqLineCount);
+    }
+
+    /**
+     * @return array<int, int>
+     */
+    private function fixPossibleAttributePhpdocSequence(Tokens $tokens, int $attributeCloseIndex, int $classStartIndex): array
```
Comment (SpacePossum) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:438]: as the function doesn't actually fix anything I think it might be better called something like `getAttributePhpdocSequenceOffsetIndex` or something like that

**Comment by SpacePossum** [comment]
I like this PR a lot and know it is a feature request for a lot for some time :+1: 

Left a minor and kicked the CI, so lets see on that. 
Another thing I was wondering is https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5704#issuecomment-864200146 , I would like the style with each PHPDoc + element being separated by itself, so basically agreeing with @ruudk . What do others think and what would  be the effort to adjust?

**Comment by keradus** [comment]
Thank you @paulbalandan.

**Comment by ruudk** [comment]
Thank you @paulbalandan for this amazing contribution ❤️ 🙌

File: src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php [hunk 9]
```diff
@@ -39,24 +41,26 @@
  */
 final class ClassAttributesSeparationFixer extends AbstractFixer implements ConfigurableFixerInterface, WhitespacesAwareFixerInterface
 {
-    /**
-     * @internal
-     */
-    public const SPACING_NONE = 'none';
+    private const SPACING_NONE = 'none';
```
Comment (SpacePossum) [inline src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:44]: @keradus @kubawerlos isn't this a BC break? changing the visibility in a minor?

Comment (kubawerlos) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:44]: I'd say no as it's `@internal`.

Comment (SpacePossum) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:44]: yeah, it wasn't, it was tagged internal because making it `private` would be a BC break so it could be done on the next major, here it is just a plain BC break, will be reverted here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5920 if someone cares

Comment (keradus) [reply src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php:44]: @SpacePossum , it was `@internal` on v3.0.0, so we can change it to private at 3.x freely
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php#L43
