### PR TITLE
BracesFixer - fix missing braces when statement is not followed by ;

### LINKED ISSUE #820: Simple if statement causes internal error
The following causes an "internal error". If the "x" is removed from the end it works.

``` php
<?php if (true) echo 's' ?>x
```

I'm running version version 1.3 according to `php-cs-fixer --version`

### PR DESCRIPTION
**Pull request by keradus**
Fix #820

### CODE REVIEW

File: Symfony/CS/Fixer/PSR2/BracesFixer.php [hunk 1]
```diff
@@ -430,11 +435,15 @@ private function findStatementEnd(Tokens $tokens, $parenthesisEndIndex)
...
+                return $index;
+            }
+
+            if ($token->isGivenKind(T_CLOSE_TAG)) {
+                return $tokens->getPrevNonWhitespace($index);
             }
         }
 
-        return $index;
+        throw new \RuntimeExpcetion('Statement end not found');
```
Comment (stof) [inline Symfony/CS/Fixer/PSR2/BracesFixer.php]: typo in the exception class name

Comment (keradus) [inline Symfony/CS/Fixer/PSR2/BracesFixer.php]: yeah
