### PR TITLE
NoUnusedImports - Fix imports detected as used in namespaces

### LINKED ISSUE #4410: no_unused_imports not working correctly
It seems like `php-cs-fixer` do not remove all unused imports.
I have provided a class (Laravel Form Request) as an example.
I'm importing 3 classes (Laravel Models), `User`, `Role`, `App`.
When running `php-cs-fixer` command listed below, it only removes `Role`, but leaves `User` and `App` even though they're not being used either.

---

For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.17

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.14.0

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix app/Admin/Http/Requests/Api/SubscribeRequest.php

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('tests/Fixtures')
    ->in(__DIR__);

$config = PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        'array_indentation' => true,
        'trailing_comma_in_multiline_array' => true,
        'method_chaining_indentation' => true,
        'binary_operator_spaces' => true,
        'strict_comparison' => true,
        'standardize_not_equals' => true,
        'strict_param' => true,
        'concat_space' => ['spacing' => 'one'],
        'array_syntax' => ['syntax' => 'short'],
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'blank_line_before_statement' => true,
        'whitespace_after_comma_in_array' => true,
    ])
    ->setFinder($finder);

return $config;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace App\Admin\Http\Requests\Api;

use App\Models\User;
use App\Models\Role;
use App\Models\App;
use App\Http\Requests\Request;

class SubscribeRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        //
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace App\Admin\Http\Requests\Api;

use App\Models\User;
use App\Models\App;
use App\Http\Requests\Request;

class SubscribeRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        //
    }
}
```

 * with the changes you expected instead:
```php
<?php

namespace App\Admin\Http\Requests\Api;

use App\Http\Requests\Request;

class SubscribeRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        //
    }
}
```

### PR DESCRIPTION
**Pull request by julienfalque**
Partially fixes #4410.

### CODE REVIEW

**Comment by SpacePossum** [comment]
looking good, please check https://github.com/julienfalque/PHP-CS-Fixer/pull/8 for one edge case

**Comment by julienfalque** [comment]
Thank you @SpacePossum :)

**Comment by erickskrauch** [comment]
Got the same bug. Is it possible to merge this fix?

File: src/Fixer/Import/NoUnusedImportsFixer.php [hunk 1]
```diff
@@ -114,9 +114,18 @@ function (NamespaceUseAnalysis $useDeclaration) use ($namespace) {
...
 
+    /**
+     * @param Tokens            $tokens
+     * @param NamespaceAnalysis $namespace
+     * @param array<int, int>   $ignoredIndexes
+     * @param string            $shortName
+     *
+     * @return bool
+     */
     private function importIsUsed(Tokens $tokens, NamespaceAnalysis $namespace, array $ignoredIndexes, $shortName)
```
Comment (kubawerlos) [inline src/Fixer/Import/NoUnusedImportsFixer.php]: Can we rename this method to `isImportUsed`?

File: src/Fixer/Import/NoUnusedImportsFixer.php [hunk 2]
```diff
@@ -114,9 +114,18 @@ function (NamespaceUseAnalysis $useDeclaration) use ($namespace) {
...
     {
-        for ($index = $namespace->getScopeStartIndex(); $index <= $namespace->getScopeEndIndex(); ++$index) {
+        $namespaceEndIndex = $namespace->getScopeEndIndex();
```
Comment (kubawerlos) [inline src/Fixer/Import/NoUnusedImportsFixer.php]: Is this assignment making the code more clear? Personally I'd put `$namespace->getScopeEndIndex()` directly in `for`, so it "makes pair" with `getScopeStartIndex` in single line.

File: src/Fixer/Import/NoUnusedImportsFixer.php (hunk 1 above)
Comment (julienfalque) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: I prefer the current name, it feels more natural.

File: src/Fixer/Import/NoUnusedImportsFixer.php (hunk 2 above)
Comment (julienfalque) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: Actually I don't remember why I made this change. Maybe I wanted to reuse the variable but then I didn't. Or I wanted to avoid a method call on each `for` iteration. I can revert it if you think it's best.

File: src/Fixer/Import/NoUnusedImportsFixer.php (hunk 1 above)
Comment (kubawerlos) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: How come it is more natural? The question "is import used?" is the right way to ask, not "import is used?". Also `is` at the beginning is the "classic" prefix for returning boolean.

Comment (julienfalque) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: I always try to think of methods as orders to give rather than questions to ask: _"Tell me whether this **import is used**"_ vs. _"**Is** this **import used**?"_.

File: src/Fixer/Import/NoUnusedImportsFixer.php (hunk 2 above)
Comment (julienfalque) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: I would keep the variable to avoid calling `$namespace->getScopeStartIndex()` for each iteration so I mark this conversation as resolved. Let me know if you prefer reverting the change instead.

File: src/Fixer/Import/NoUnusedImportsFixer.php (hunk 1 above)
Comment (kubawerlos) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: > I always try to think of methods as orders

Me too, when possible, yet this case is yes/no question after all.

Comment (julienfalque) [reply src/Fixer/Import/NoUnusedImportsFixer.php]: Method renamed.

**Comment by SpacePossum** [comment]
Thank you @julienfalque.
