### PR TITLE
TypeAlternationTransformer - Fix pipes in function call with constants being classified incorrectly

### LINKED ISSUE #4008: Rule native_constant_invocation doesn't work in some cases
#### The PHP version you are using (`$ php -v`):
=> 7.1.22

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.0 Yogi's BBQ

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix . --rules=native_constant_invocation --allow-risky=yes`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function doSth($bitmask) {
}

doSth(E_DEPRECATED | E_USER_DEPRECATED);

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

function doSth($bitmask) {
}

doSth(E_DEPRECATED | \E_USER_DEPRECATED);

```

 * with the changes you expected instead:
```php
<?php

function doSth($bitmask) {
}

doSth(\E_DEPRECATED | \E_USER_DEPRECATED);

```

### PR DESCRIPTION
**Pull request by ntzm**
Closes #4008

### CODE REVIEW

**Comment by SpacePossum** [comment]
can you add this test case:

```php
<?php
try {
    foo(\JSON_ERROR_DEPTH|JSON_PRETTY_PRINT|\JOB_QUEUE_PRIORITY_HIGH);
} catch (\Exception | \InvalidArgumentException|\UnexpectedValueException|LogicException $e) {
}
```

File: tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php [hunk 1]
```diff
@@ -189,6 +189,24 @@ public function provideFixWithDefaultConfigurationCases()
...
+            ],
+            [
+                '<?php
+try {
+    foo(\JSON_ERROR_DEPTH|\JSON_PRETTY_PRINT|\JOB_QUEUE_PRIORITY_HIGH);
+} catch (\Exception | \InvalidArgumentException|\UnexpectedValueException|LogicException $e) {
+}
+',
+                '<?php
+try {
```
Comment (SpacePossum) [inline tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php]: @ntzm your work looks good :)

However the tests are failing, this is because these tests should only run on PHP7.1 or up, below this syntax is not supported. Please update than we are close to merging :+1:

Comment (ntzm) [reply tests/Fixer/ConstantNotation/NativeConstantInvocationFixerTest.php]: Oops, my bad

**Comment by SpacePossum** [comment]
@ntzm please check my last two commits and let me know what you think :)

**Comment by ntzm** [comment]
I'll take a look tomorrow, thanks for fixing, been a bit short on time recently

**Comment by ntzm** [comment]
LGTM @SpacePossum, thanks for picking it up

**Comment by SpacePossum** [comment]
Thank you @ntzm.
