### PR TITLE
PhpUnitNamespacedFixer - properly translate classes which do not follow translation pattern

### LINKED ISSUE #4417: PHP Parse error @PHPUnit60Migration
When using the _@PHPUnit60Migration:riky_ ruleset (effectively the **PhpUnitNamespacedFixer**) PHP-CS-Fixer was not able to fix files due to resulting the fixes into a PHP Parse error:

> PHP Parse error: syntax error, unexpected 'Return' (T_RETURN), expecting identifier (T_STRING)

This is when changing the class **PHPUnit_Framework_MockObject_Stub_Return** into the new namespaced  class **PHPUnit\Framework\MockObject\Stub\Return**.

Changing the class-name string `PHPUnit_Framework_MockObject_Stub_Return` to `PHPUnit_Framework_MockObject_Stub_ReturnStub` results in the correct new type `PHPUnit\Framework\MockObject\Stub\ReturnStub`.

---

#### The command you use to run PHP CS Fixer:
~~~
php7.1 -n -dextension=tokenizer.so -dextension=json.so -dextension=ctype.so -dextension=iconv.so \
  -f../PHP-CS-Fixer/php-cs-fixer -- fix -vvv \
  --rules=@PHPUnit60Migration:risky,-php_unit_mock \
  tests
~~~

### PR DESCRIPTION
**Pull request by ktomk**
Fixes #4417

When cs-fix the name-space of the class

    PHPUnit_Framework_MockObject_Stub_Return

it results in a new class name which causes a PHP parse error b/c of the
reserved word "return" as the new class-name.

Phpunit has renamed that class to ...\ReturnStub (5 -> 6).

Fix is to translate it to the "new" name so that it transposes correctly.

Fixer: PhpUnitNamespacedFixer

### CODE REVIEW

**Comment by ktomk** [comment]
Another candidate that could benefit from the translation is:

* `PHPUnit_Framework_Error` -> `PHPUnit\Framework\Error\Error`

**Comment by ktomk** [comment]
Added a full translation table, could only **not** find the following Phpunit 5 counterparts:

* PHPUnit_Extensions_TicketListener (-> PHPUnit\Extensions\TicketListener)
* PHPUnit_Extensions_PhptTestSuite (-> PHPUnit\Extensions\PhptTestSuite)
* PHPUnit_Extensions_TestDecorator (-> PHPUnit\Extensions\TestDecorator)
* PHPUnit_Extensions_RepeatedTest (-> PHPUnit\Extensions\RepeatedTest)
* PHPUnit_Extensions_GroupTestSuite (-> PHPUnit\Extensions\GroupTestSuite)
* PHPUnit_Util_Log_JSON (-> PHPUnit\Util\Log\JSON)
* PHPUnit_Util_Log_TAP (-> PHPUnit\Util\Log\TAP)
* PHPUnit_Util_String (-> PHPUnit\Util\String)
* PHPUnit_Util_PHPTest (-> PHPUnit\Util\PHPTest)

**Comment by keradus** [comment]
Nice PR @ktomk !

File: src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php [hunk 1]
```diff
@@ -81,10 +86,41 @@ public function configure(array $configuration = null)
...
         if (PhpUnitTargetVersion::fulfills($this->configuration['target'], PhpUnitTargetVersion::VERSION_6_0)) {
             $this->originalClassRegEx = '/^PHPUnit_\w+$/i';
+            $this->originalClassTranslations = [
+                'PHPUnit_Extensions_PhptTestCase' => 'PHPUnit_Runner_PhptTestCase',
+                'PHPUnit_Framework_Constraint' => 'PHPUnit_Framework_Constraint_Constraint',
+                'PHPUnit_Framework_Constraint_StringMatches' => 'PHPUnit_Framework_Constraint_StringMatchesFormatDescription',
+                'PHPUnit_Framework_Constraint_JsonMatches_ErrorMessageProvider' => 'PHPUnit_Framework_Constraint_JsonMatchesErrorMessageProvider',
+                'PHPUnit_Framework_Constraint_PCREMatch' => 'PHPUnit_Framework_Constraint_RegularExpression',
+                'PHPUnit_Framework_Constraint_ExceptionMessageRegExp' => 'PHPUnit_Framework_Constraint_ExceptionMessageRegularExpression',
+                'PHPUnit_Framework_Constraint_And' => 'PHPUnit_Framework_Constraint_LogicalAnd',
```
Comment (keradus) [inline src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php]: if I get this right, `PHPUnit_Framework_Constraint_LogicalAnd`  was never existing. It was introduced alread with `\` (`PHPUnit\Framework\Constraint\LogicalAnd`).

for that, currently, your proposal:
- takes original name
- translates it to fake name that would follow transition pattern
- applies transition pattern

we can simplify it that this table can contain already ready to use name with `\`, and then:
- if original name exists in dictionary, use name from dictionary
- if not, apply transition pattern

**Comment by keradus** [comment]
please, change target branch to 2.12 LTS line

File: src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php [hunk 2]
```diff
@@ -32,6 +32,11 @@ final class PhpUnitNamespacedFixer extends AbstractFixer implements Configuratio
      */
     private $originalClassRegEx;
 
+    /**
+     * @var array|string[]
+     */
+    private $originalClassTranslations;
```
Comment (keradus) [inline src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php]: please add reasoning for this array in description
like why we need to have it in first place. for now, it's hidden knowledge why some classes are put here and some are not

File: src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php (hunk 1 above)
Comment (ktomk) [reply src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php]: This is equally possible, yes. It would spare any fake names. This is straight to update, but needs more branching in the old translation function. It might be more clear however when looking at the bare data that the map is old => new. I'll change it to that, this can be part of the next review iteration.

**Comment by ktomk** [comment]
About the tests, is there some boilerplate I can reuse? I have it functionally tested here as I run the conversion currently which is how I've detected the original error. So if you can point to some file with a link would be helpful to get me started with fixer tests.

**Comment by ktomk** [comment]
@keradus I fully addressed your comments.

File: src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php (hunk 2 above)
Comment (ktomk) [reply src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php]: thanks for pointing to that, I removed the indirection and made it a more direct old => new class-map now and explained that it assists the regex which provides the foremost class detection and helps out for those cases where it matches but *"do[es] not have a same-compound namespace class and need a dedicated translation table."*. Also referencing *`configure()`* method which now has the array configuration below the regex nicely paired.

File: src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php (hunk 1 above)
Comment (ktomk) [reply src/Fixer/PhpUnit/PhpUnitNamespacedFixer.php]: There are no more fake names, it's just old => new now, and new is already with namespace separators.

**Comment by keradus** [comment]
Thank you @ktomk.

**Comment by ktomk** [comment]
@keradus: You're welcome, and thank you for having me here. Let's see for the next Phpunit conversion :)
