### PR TITLE
PhpdocVarWithoutNameFixer - fix for properties only

### LINKED ISSUE #3112: Change rules of PhpdocVarWithoutNameFixer
`phpdoc_var_without_name` fixer has some internal rules to decide whether the `$varname` part of a `@var` PHPDoc tag should be removed:
- ignore DocComments when they are on a single line, e.g. `/** @var Foo $foo */`;
- ignore `@var` tags that are not the first tag in the DocComment.

IMO these rules are wrong, I would replace them with a new rule: the fixer should simply ignore DocComments that don't apply to a class property.

### PR DESCRIPTION
**Pull request by dmvdbrugge**
This fixes #3112

### CODE REVIEW

File: src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php [hunk 1]
```diff
@@ -68,21 +68,30 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens)
...
 
-            $doc = new DocBlock($token->getContent());
+            $nextIndex = $tokens->getNextMeaningfulToken($index);
+            $nextToken = isset($tokens[$nextIndex]) ? $tokens[$nextIndex] : null;
 
-            // don't process single line docblocks
-            if (1 === count($doc->getLines())) {
-                continue;
+            // For people writing static public $foo instead of public static $foo
+            if ($nextToken && $nextToken->isGivenKind([T_STATIC])) {
```
Comment (ntzm) [inline src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: Better to be strict and check `$nextToken !== null` or `$nextToken instanceof Token`

File: src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php [hunk 2]
```diff
@@ -68,21 +68,30 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens)
...
+                $nextIndex = $tokens->getNextMeaningfulToken($nextIndex);
+                $nextToken = isset($tokens[$nextIndex]) ? $tokens[$nextIndex] : null;
             }
 
-            $annotations = $doc->getAnnotationsOfType(['param', 'return', 'type', 'var']);
-
-            // only process docblocks where the first meaningful annotation is @type or @var
-            if (!isset($annotations[0]) || !in_array($annotations[0]->getTag()->getName(), ['type', 'var'], true)) {
+            // We want only doc blocks that are for properties and thus have specified access modifiers next
+            if (!$nextToken || !$nextToken->isGivenKind([T_PRIVATE, T_PROTECTED, T_PUBLIC])) {
```
Comment (ntzm) [inline src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: Strict check here too

File: tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test [hunk 3]
```diff
@@ -1,26 +0,0 @@
---TEST--
-Integration of fixers: phpdoc_to_comment,phpdoc_var_without_name.
```
[the remark this answers is not in the document]
Comment (dmvdbrugge) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: It's a useless test that tests nothing, both fixers have no effect on the given code, as is already proven by their unit tests. There is no interaction going on between these fixers, so this test serves no use.

"Do not remove tests" sounds like a rule without reason. Can you tell me why this test should exist?

[the remark this answers is not in the document]
Comment (keradus) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: for dropping test you assume it's pointless
for keeping it, we ensure that when test was introduced to ensure something works, we don't break that by accident, because we happily drop testing that.

I prefer to have 10 tests that test nothing than drop one test that one only thought it doesn't test a thing.

Test here was added as proof that false-positive is not happening anymore, so prove that bug we had was fixed. That means originally, this code was wrongly changed.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2191

File: src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php [hunk 4]
```diff
@@ -68,21 +68,30 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens)
...
             }
 
-            $doc = new DocBlock($token->getContent());
+            $nextIndex = $tokens->getNextMeaningfulToken($index);
+            $nextToken = isset($tokens[$nextIndex]) ? $tokens[$nextIndex] : null;
 
-            // don't process single line docblocks
-            if (1 === count($doc->getLines())) {
-                continue;
+            // For people writing static public $foo instead of public static $foo
```
Comment (ntzm) [inline src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: Any tests to demonstrate this behaviour? Only seems to be tests for `public` properties atm, could do with ones for `static`, `private`, `protected` and `var`

File: src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php [hunk 5]
```diff
@@ -20,6 +20,7 @@
 use PhpCsFixer\Preg;
 use PhpCsFixer\Tokenizer\Token;
 use PhpCsFixer\Tokenizer\Tokens;
+use const T_VAR;
```
Comment (kubawerlos) [inline src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: What is the reason for this import?

Comment (dmvdbrugge) [reply src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: PhpStorm settings I use in personal projects

`use` :allthethings:

Should've seen and removed that. Will do so now 😄

File: tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test [hunk 6]
```diff
@@ -8,19 +8,35 @@ Integration of fixers: phpdoc_to_comment,phpdoc_var_without_name.
 --EXPECT--
 <?php
 
-$first = true;// needed because by default first docblock is never fixed.
+/**
```
Comment (kubawerlos) [inline tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: What is the point of this test? `phpdoc_to_comment` is not doing anything here (neither it was before changes).

Maybe... maybe we can have a docblock with a var name to remove, and `phpdoc_to_comment` would change it to comment before `phpdoc_var_without_name` would remove the name - but personally I'd remove this test.

**Comment by kubawerlos** [comment]
@keradus @ntzm can you check it and update you review status?

File: tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test (hunk 6 above)
Comment (dmvdbrugge) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: This is exactly why I initially deleted this test, however @keradus was totally against it, as can be seen [in the discussion above](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3911#discussion_r202309642).

File: src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php [hunk 7]
```diff
@@ -68,21 +69,30 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens)
...
+                $nextIndex = $tokens->getNextMeaningfulToken($nextIndex);
+                $nextToken = isset($tokens[$nextIndex]) ? $tokens[$nextIndex] : null;
             }
 
-            $annotations = $doc->getAnnotationsOfType(['param', 'return', 'type', 'var']);
-
-            // only process docblocks where the first meaningful annotation is @type or @var
-            if (!isset($annotations[0]) || !\in_array($annotations[0]->getTag()->getName(), ['type', 'var'], true)) {
+            // We want only doc blocks that are for properties and thus have specified access modifiers next
+            if (null === $nextToken || !$nextToken->isGivenKind([T_PRIVATE, T_PROTECTED, T_PUBLIC, T_VAR])) {
```
Comment (SpacePossum) [inline src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: Maybe you can utilize `TokensAnalyzer::getClassyElements` to prevent have this kind of logic duplicated in the code base. Please add a unit test for nested anonymous classes as well.

Comment (dmvdbrugge) [reply src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: - [X] Nested anonymous classes testcase
- [ ] Try `TokensAnalyzer::getClassyElements`

Comment (dmvdbrugge) [reply src/Fixer/Phpdoc/PhpdocVarWithoutNameFixer.php]: I've looked into `TokensAnalyzer::getClassyElements` however I don't see it becoming cleaner code:

- If working forward from the doc block (like now) we still need a way to match it to the classy element it belongs to.
- If working backwards from the classy elements, we still need to traverse back to find the actual matching doc block if any (and not any intermediary comment that happens to be like `/** this */`) which can be any number of tokens away from the index of the classy element.

**Comment by enumag** [comment]
Can this be merged?

**Comment by SpacePossum** [comment]
@kubawerlos or members/maintainer please review/approve as well

**Comment by enumag** [comment]
Another month passed... Can someone please take a look? @keradus?

**Comment by dmvdbrugge** [comment]
I rebased onto latest 2.12

Travis fails on something completely unrelated to this PR 😕

File: tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test [hunk 8]
```diff
@@ -8,19 +8,35 @@ Integration of fixers: phpdoc_to_comment,phpdoc_var_without_name.
 --EXPECT--
```
Comment (keradus) [inline tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3911#discussion_r202366775
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3911/files#r208303314

basically, this test got rewritten.

I just tested locally original test against code changes proposed by this PR - the test is failing. This means that the rule behind the fixer got modified, and test that has to be changed (regardless if it's utest or itest) proves that.
I find this to be a BC breaker - if a fixer apply single rule in multiple places (like here - for properties and for variables), and you want to adjust the scope and allow to fix only some of places - it deserves configurable option. If you want to fix only some of places without being able to configure it, it's a BC breaker for the rule.

Now, if I would merge it, nobody would be able to apply the rule for variables.

Comment (keradus) [inline tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3911#discussion_r202366775
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3911/files#r208303314

basically, this test got rewritten.

I just tested locally original test against code changes proposed by this PR - the test is failing. This means that the rule behind the fixer got modified, and test that has to be changed (regardless if it's utest or itest) proves that.
I find this to be a BC breaker - if a fixer apply single rule in multiple places (like here - for properties and for variables), and you want to adjust the scope and allow to fix only some of places - it deserves configurable option. If you want to fix only some of places without being able to configure it, it's a BC breaker for the rule.

Now, if I would merge it, nobody would be able to apply the rule for variables.

Comment (dmvdbrugge) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: @julienfalque can you weigh in here? Wasn't this the entire point of your issue?

Comment (keradus) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: if someone wants to apply the rule only for properties, i'm fine with that.
but allowing to do so must not disallow to apply the rule for variables, as this is the behaviour we currently have - thus changing the rule in a way that variables will not be modified anymore is BC breaker.

I agree - i am not fully aware about the concerns or issues and i'm far from judging should we fix only properties or everyone - I'm only watching after keeping BC.

Comment (julienfalque) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: From [phpDocumentator doc](https://docs.phpdoc.org/references/phpdoc/tags/var.html) and [PSR-19 PHPDoc tags](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#description-16):
> The `@var` tag MUST contain the name of the element it documents. An exception to this is when property declarations only refer to a single property. In this case the name of the property MAY be omitted.

IMO the current behavior of the fixer is wrong, I consider changing it a bugfix and I'm fine with breaking BC here.

File: tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php [hunk 9]
```diff
@@ -172,21 +295,156 @@ public function provideFixVarCases()
...
+                {
+                    /**
+                     * @var $stringVar string
+                     */
+                    public $stringVar;
+                };
+            }
+        };
+    }
+}
```
Comment (julienfalque) [inline tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php]: @dmvdbrugge Could you add a test case with multiple properties such as e.g.:
```php
class Foo {
    /**
     * @var int $foo
     */
    private $foo, $bar;
}
```

In such case, the variable name should not be removed from the `@var` tag as it would become ambiguous.

Also [PSR-19](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#examples-15) shows a sample with variation of this scenario but I'm not sure we should explicitly support it for now as PSR-19 is still a draft.

```php
class Foo {
    private
        /**
         * @var int
         */
        $foo,
        /**
         * @var int
         */
        $bar;
}
```

File: tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test (hunk 8 above)
Comment (keradus) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: If the fixer would be:
> `@var` tag must follow 5.17 of PSR-19 proposal

I would agree.

Yet, it's different:
```
ker@dus:~/github/PHP-CS-Fixer λ php php-cs-fixer describe phpdoc_var_without_name
Description of phpdoc_var_without_name rule.
`@var` and `@type` annotations should not contain the variable name.
```

then, i would suggest to:
- make one fixer like `phpdoc_property_var_without_name` (this PR, just new fixer instead of modifying existing)
- deprecate existing fixer
- add fixer like `phpdoc_variable_var_with_name` (our current, existing fixer does the oposite) - of course, a separated rule

**Comment by enumag** [comment]
ping @dmvdbrugge

**Comment by SpacePossum** [comment]
Thank you @dmvdbrugge.

File: tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test (hunk 8 above)
Comment (SpacePossum) [reply tests/Fixtures/Integration/misc/phpdoc_to_comment,phpdoc_var_without_name.test]: I considered the old working of the fixer a bug as well, together with other members and as such merged this.
I've updated the description to be more precise on the working of the fixer. If anyone needs the `phpdoc_variable_var_with_name` fixer than a PR is welcome.

File: tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php (hunk 9 above)
Comment (SpacePossum) [reply tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php]: The scope of this issue was to only fix classy properties. I think that the request made here is out of scope and can be resolved with a new issue and PR

**Comment by SpacePossum** [comment]
I've update the PR and added some tests and made other minor adjustments.

Thanks @dmvdbrugge for all the work, thanks to the reviewers as well!

**Comment by dmvdbrugge** [comment]
Thank you @SpacePossum for the merge and additional work. I apologise for being a bit unresponsive on this 😅
